name: Update GitHub Profile

on:
  schedule:
    # Runs at midnight UTC (adjust as needed)
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdownify PyGithub
          
      - name: Fetch PyPI Projects
        run: |
          python .github/scripts/fetch_pypi_projects.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update profile README with latest activity'
          MAX_LINES: 5
          GH_USERNAME: subaashnair
          TARGET_FILE: 'README.md'
          
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Update profile README" || exit 0
          git push 